@extends('layouts.app')
@section('content')
<div class="page-head"><div><p class="eyebrow">VUE D’ENSEMBLE</p><h2>Votre activité en un regard</h2></div><a class="primary-button" href="{{ route('campaigns.create') }}"><span>＋</span> Nouvelle campagne</a></div>

<section class="hero-panel">
    <div><div class="hero-chip"><span class="pulse"></span> VOTRE CENTRE DE MESSAGERIE</div><h2>Parlez à votre audience,<br><span>sans friction.</span></h2><p>Importez vos contacts, choisissez votre canal et laissez SEND orchestrer vos envois.</p><a href="{{ route('campaigns.create') }}" class="text-link">Lancer une campagne <span>→</span></a></div>
    <div class="hero-visual"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="hero-phone"><div class="phone-top"><span></span><span></span></div><div class="bubble bubble-top">Votre campagne est prête.</div><div class="bubble bubble-bottom">C’est parti ✦</div><div class="phone-bar"></div></div><span class="float-pill pill-sms">SMS <b>✓</b></span><span class="float-pill pill-wa">WhatsApp <b>✓</b></span></div>
</section>

<section class="stats-grid">
    <div class="stat-card"><div class="stat-icon violet">◌</div><div><span>Contacts actifs</span><strong>{{ number_format($stats['contacts'], 0, ',', ' ') }}</strong><small class="neutral">Votre carnet grandit</small></div></div>
    <div class="stat-card"><div class="stat-icon cyan">◎</div><div><span>Groupes créés</span><strong>{{ number_format($stats['groups'], 0, ',', ' ') }}</strong><small class="neutral">Pour mieux cibler</small></div></div>
    <div class="stat-card"><div class="stat-icon orange">✦</div><div><span>Campagnes lancées</span><strong>{{ number_format($stats['campaigns'], 0, ',', ' ') }}</strong><small class="neutral">Toutes périodes</small></div></div>
    <div class="stat-card"><div class="stat-icon green">✓</div><div><span>Messages envoyés</span><strong>{{ number_format($stats['sent'], 0, ',', ' ') }}</strong><small class="positive">Historique confirmé</small></div></div>
</section>

<div class="content-grid two-thirds"><section class="panel"><div class="section-head"><div><p class="eyebrow">VOS DERNIÈRES CAMPAGNES</p><h3>Suivez vos envois</h3></div><a class="subtle-link" href="{{ route('campaigns.index') }}">Tout voir →</a></div><div class="campaign-list">
    @forelse($campaigns as $campaign)<a class="campaign-row" href="{{ route('campaigns.show', $campaign) }}"><div class="campaign-symbol {{ $campaign->channel }}">{{ $campaign->channel === 'sms' ? '✉' : '◉' }}</div><div class="campaign-main"><strong>{{ $campaign->name }}</strong><span>{{ $campaign->group->name }} · {{ $campaign->created_at->diffForHumans() }}</span></div><div class="campaign-progress"><div class="progress-track"><i style="width: {{ $campaign->total_recipients ? min(100, ($campaign->sent_count / $campaign->total_recipients) * 100) : 0 }}%"></i></div><span>{{ $campaign->sent_count }}/{{ $campaign->total_recipients }}</span></div><span class="status-pill {{ $campaign->status }}">{{ ['queued'=>'En file','processing'=>'En cours','completed'=>'Terminée','partial'=>'Partielle','failed'=>'Échec','draft'=>'Brouillon'][$campaign->status] ?? $campaign->status }}</span></a>@empty <div class="empty-state"><span>✦</span><p>Aucune campagne pour le moment.</p><a class="text-link" href="{{ route('campaigns.create') }}">Créer la première →</a></div>@endforelse
</div></section><section class="panel balance-panel"><div class="section-head"><div><p class="eyebrow">VOS CRÉDITS</p><h3>Solde disponible</h3></div><a class="icon-button small" href="{{ route('quota.index') }}">＋</a></div><div class="balance-visual"><div class="balance-ring"><div><strong>{{ number_format($user->sms_credits + $user->whatsapp_credits, 0, ',', ' ') }}</strong><span>crédits</span></div></div></div><div class="balance-lines"><div><span><i class="dot sms"></i> SMS</span><strong>{{ number_format($user->sms_credits, 0, ',', ' ') }}</strong></div><div><span><i class="dot wa"></i> WhatsApp</span><strong>{{ number_format($user->whatsapp_credits, 0, ',', ' ') }}</strong></div></div><a class="secondary-button wide" href="{{ route('quota.index') }}">Acheter des crédits <span>→</span></a></section></div>

<section class="panel activity-panel"><div class="section-head"><div><p class="eyebrow">ACTIVITÉ RÉCENTE</p><h3>Les derniers destinataires</h3></div><a class="subtle-link" href="{{ route('history.index') }}">Voir l’historique →</a></div><div class="table-wrap"><table><thead><tr><th>DESTINATAIRE</th><th>CANAL</th><th>DATE</th><th>ÉTAT</th></tr></thead><tbody>@forelse($deliveries as $delivery)<tr><td><div class="person-cell"><span class="avatar avatar-tiny">{{ strtoupper(substr($delivery->contact->name, 0, 1)) }}</span><div><strong>{{ $delivery->contact->name }}</strong><small>{{ $delivery->contact->phone }}</small></div></div></td><td><span class="channel-label {{ $delivery->campaign->channel }}">{{ $delivery->campaign->channel === 'sms' ? 'SMS' : 'WhatsApp' }}</span></td><td>{{ $delivery->last_attempt_at?->format('d/m/Y · H:i') ?? '—' }}</td><td><span class="status-pill {{ $delivery->status }}">{{ $delivery->status === 'sent' ? 'Envoyé' : ($delivery->status === 'failed' ? 'Échoué' : 'En attente') }}</span></td></tr>@empty <tr><td colspan="4" class="table-empty">Votre activité apparaîtra ici.</td></tr>@endforelse</tbody></table></div></section>
@endsection
